### ISSUE TITLE
default address is 0x44

### ISSUE THREAD

**Issue by tedhuntington** [mongoose-os-libs/sht31-i2c#2]
I think the default address is 0x44, alt is 0x45 but you have 0x40

**Comment by pimvanpelt** [comment]
Confirmed -- datasheet mentions:

I2C address A 0x44 (default) ADDR (pin 2) connected to VSS
I2C address B 0x45 ADDR (pin 2) connected to VDD

**Comment by pimvanpelt** [comment]
Fixed in https://github.com/mongoose-os-libs/sht31-i2c/commit/9b7a381555295d1b287629716527a7c807a46877
